version: '3.3'

services:
  warlords-server:
    container_name: warlords-server
    image: jacekku/warlords-online:latest
    command: npm run start:prod
    networks:
      - nestjs-network
    volumes:
      - .:/usr/warlords/
      - /etc/letsencrypt/live/warlordsonline.net/fullchain.pem:/usr/warlords/fullchain.pem
      - /etc/letsencrypt/live/warlordsonline.net/privkey.pem:/usr/warlords/privkey.pem

    ports:
      - 3000:3000
      - 9229:9229
    environment:
      SAVE_FOLDER: '/usr/warlords/saves'
      DEFAULT_TERRAIN:
      FRUSTUM_SIZE: 13
networks:
  nestjs-network:
