version: '3.3'

services:
  warlords-server:
    container_name: warlords-server
    image: jacekku/warlords-online:latest
    command: npm run start:prod
    networks:
      - nestjs-network
    volumes:
      - .:/usr/warlords/
      - ./fullchain.pem:/usr/warlords/fullchain.pem
      - ./privkey.pem:/usr/warlords/privkey.pem
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      SAVE_FOLDER: '/usr/warlords/saves'
      DEFAULT_TERRAIN: d5da909c9
      FRUSTUM_SIZE: 13
      CORS_ORIGIN: 'https://warlordsonline.net'
      PERSISTENCE_TYPE: mongodb
      MONGO_HOST: mongodb #name of container with mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: warlordsOnline
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    networks:
      - nestjs-network

networks:
  nestjs-network:
