version: '3.3'

services:
  warlords-server:
    container_name: warlords-server
    image: warlords-online:local
    command: npm run start:prod
    networks:
      - nestjs-network
    volumes:
      - .:/usr/warlords/
      - ./fullchain.pem:/usr/warlords/fullchain.pem
      - ./privkey.pem:/usr/warlords/privkey.pem
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      SAVE_FOLDER: '/usr/warlords/saves'
      DEFAULT_TERRAIN: e5e745c54
      FRUSTUM_SIZE: 13
      ENVIRONMENT: DEV
      CORS_ORIGIN: https://warlordsonline.net,http://localhost:5501,http://localhost:5500
      JWT_SECRET_URL: 'https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com'
      PERSISTENCE_TYPE: file
      MONGO_HOST: mongodb #name of container with mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: warlordsOnline
      ADMINS: Mqk2cA2buCMW5NVa4usyfPkJYZi2
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    networks:
      - nestjs-network

networks:
  nestjs-network:
