export const TERRAIN_PERSISTENCE_SERVICE = 'TERRAIN_PERSISTENCE_SERVICE';
export const USERS_PERSISTENCE_SERVICE = 'USERS_PERSISTENCE_SERVICE';
export const BUILDINGS_PERSISTENCE_SERVICE = 'BUILDINGS_PERSISTENCE_SERVICE';
export const PERSISTENCE_TYPE = 'PERSISTENCE_TYPE';
